spring:
  datasource: #DB 커넥션 관련 설정
    url: jdbc:h2:tcp://localhost/~/jpashop;MODE=MYSQL # ;MVCC=true 옵션 추가  시 여러 커넥션 접근 시 속도가 좀 더 빨라짐, 추가 권장
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #create: 애플리케이션 실행 시점에 엔티티를 보고 테이블을 다시 만듦, none: 테이블 유지
    properties: #hibernate 관련 상세 설정, Spring boot 메뉴얼에서 다양한 설정 확인 가능
      hibernate:
#        show_sql: true
        format_sql: true #sout으로 찍히기 때문에 운영환경에서는 제외해야한다.
        default_batch_fetch_size: 100 #왠만하면 이 옵션을 켜는 것이 좋다.
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

h2:
  console:
    enabled: true
    path: /h2-console

logging:
  level:
      org.hibernate.SQL: debug #hibernate가 생성한 모든 로그가 디버그 로그로 출력됨

