spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #create: ?????? ?? ??? ???? ?? ???? ?? ??, none: ??? ??
    properties: #hibernate ?? ?? ??, Spring boot ????? ??? ?? ?? ??
      hibernate:
        format_sql: true #show_sql:true? sout?? ??? ??? ??????? ??????.
        default_batch_fetch_size: 100 #???? ? ??? ?? ?? ??.

  logging:
    level:
      org.hibernate.SQL: debug #hibernate? ??? ?? ??? ??? ??? ???
      #org.hibernate.type: trace #????? ???? ?? ? ? ??
      p6spy: info
