spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true #qureyDSL의 JPQL을 조회할 수 있다.
        default_batch_fetch_size: 100

  logging:
    level:
      org.hibernate.SQL: debug
      #org.hibernate.type: trace
      p6spy: info

  decorator:
    datasource:
      p6spy:
        enable-logging: true
